![The Big Project](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbd6xLmhSYkowGGJSgTogOqZ10Q7mp3_BFMA&s)

*DATA MANAGEMENT PROJECT*

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob

In [3]:
files = glob.glob('JC-2016*-citibike-tripdata.csv')

In [4]:
print(files)

['JC-201601-citibike-tripdata.csv', 'JC-201602-citibike-tripdata.csv', 'JC-201603-citibike-tripdata.csv', 'JC-201604-citibike-tripdata.csv', 'JC-201605-citibike-tripdata.csv', 'JC-201606-citibike-tripdata.csv', 'JC-201607-citibike-tripdata.csv', 'JC-201608-citibike-tripdata.csv', 'JC-201609-citibike-tripdata.csv', 'JC-201610-citibike-tripdata.csv', 'JC-201611-citibike-tripdata.csv', 'JC-201612-citibike-tripdata.csv']

In [5]:
df_list = [pd.read_csv(file) for file in files]

In [6]:
df = pd.concat(df_list)

In [7]:
df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender
0,362,2016-01-01 00:02:52,2016-01-01 00:08:54,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,24647,Subscriber,1964.0,2
1,200,2016-01-01 00:18:22,2016-01-01 00:21:42,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24605,Subscriber,1962.0,1
2,202,2016-01-01 00:18:25,2016-01-01 00:21:47,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24689,Subscriber,1962.0,2
3,248,2016-01-01 00:23:13,2016-01-01 00:27:21,3209,Brunswick St,40.724176,-74.050656,3203,Hamilton Park,40.727596,-74.044247,24693,Subscriber,1984.0,1
4,903,2016-01-01 01:03:20,2016-01-01 01:18:24,3195,Sip Ave,40.730743,-74.063784,3210,Pershing Field,40.742677,-74.051789,24573,Customer,NaN,0

In [8]:
df.isnull().sum()

Trip Duration                  0
Start Time                     0
Stop Time                      0
Start Station ID               0
Start Station Name             0
Start Station Latitude         0
Start Station Longitude        0
End Station ID                 0
End Station Name               0
End Station Latitude           0
End Station Longitude          0
Bike ID                        0
User Type                    380
Birth Year                 18999
Gender                         0
dtype: int64

In [9]:
df.dtypes

Trip Duration                int64
Start Time                  object
Stop Time                   object
Start Station ID             int64
Start Station Name          object
Start Station Latitude     float64
Start Station Longitude    float64
End Station ID               int64
End Station Name            object
End Station Latitude       float64
End Station Longitude      float64
Bike ID                      int64
User Type                   object
Birth Year                 float64
Gender                       int64
dtype: object

In [10]:
df.describe()

,Trip Duration,Start Station ID,Start Station Latitude,Start Station Longitude,End Station ID,End Station Latitude,End Station Longitude,Bike ID,Birth Year,Gender
count,2.475840e+05,247584.000000,247584.000000,247584.000000,247584.000000,247584.000000,247584.000000,247584.000000,228585.000000,247584.000000
mean,8.856305e+02,3207.065206,40.723121,-74.046438,3203.572553,40.722594,-74.045855,24935.260481,1979.335276,1.123534
std,3.593798e+04,26.955103,0.008199,0.011211,61.579494,0.007958,0.011283,748.469712,9.596809,0.518687
min,6.100000e+01,3183.000000,40.692640,-74.096937,147.000000,40.692216,-74.096937,14552.000000,1900.000000,0.000000
25%,2.480000e+02,3186.000000,40.717732,-74.050656,3186.000000,40.716540,-74.050444,24491.000000,1974.000000,1.000000
50%,3.900000e+02,3201.000000,40.721525,-74.044247,3199.000000,40.721124,-74.043117,24609.000000,1981.000000,1.000000
75%,6.660000e+02,3211.000000,40.727596,-74.038051,3211.000000,40.727224,-74.036486,24719.000000,1986.000000,1.000000
max,1.632981e+07,3426.000000,40.752559,-74.032108,3426.000000,40.801343,-73.957390,27274.000000,2000.000000,2.000000

In [11]:
split_repdate = df['Start Time'].str.split('-', expand=True)[0]

In [12]:
split_repdate

0        2016
1        2016
2        2016
3        2016
4        2016
         ...
15109    2016
15110    2016
15111    2016
15112    2016
15113    2016
Name: 0, Length: 247584, dtype: object

In [13]:
df['year_of_ride'] = pd.to_numeric(split_repdate)

In [14]:
df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender,year_of_ride
0,362,2016-01-01 00:02:52,2016-01-01 00:08:54,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,24647,Subscriber,1964.0,2,2016
1,200,2016-01-01 00:18:22,2016-01-01 00:21:42,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24605,Subscriber,1962.0,1,2016
2,202,2016-01-01 00:18:25,2016-01-01 00:21:47,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24689,Subscriber,1962.0,2,2016
3,248,2016-01-01 00:23:13,2016-01-01 00:27:21,3209,Brunswick St,40.724176,-74.050656,3203,Hamilton Park,40.727596,-74.044247,24693,Subscriber,1984.0,1,2016
4,903,2016-01-01 01:03:20,2016-01-01 01:18:24,3195,Sip Ave,40.730743,-74.063784,3210,Pershing Field,40.742677,-74.051789,24573,Customer,NaN,0,2016

In [15]:
df['Start Time']=pd.to_datetime(df['Start Time'])
df['Stop Time'] = pd.to_datetime(df['Stop Time'])

In [16]:
df['Month'] = df['Start Time'].dt.strftime('%m')

In [17]:
df['Gender'].value_counts()

Gender
1    177197
2     50486
0     19901
Name: count, dtype: int64

In [18]:
df['Gender'].replace(1, 'Male', inplace = True)
df['Gender'].replace(2, 'Female', inplace = True)
df['Gender'].replace(0, 'Unknown', inplace = True)

C:\Users\gelsc\AppData\Local\Temp\ipykernel_18364\3846117664.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].replace(1, 'Male', inplace = True)

In [19]:
df['Gender'].value_counts()

Gender
Male       177197
Female      50486
Unknown     19901
Name: count, dtype: int64

In [20]:
df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender,year_of_ride,Month
0,362,2016-01-01 00:02:52,2016-01-01 00:08:54,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,24647,Subscriber,1964.0,Female,2016,01
1,200,2016-01-01 00:18:22,2016-01-01 00:21:42,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24605,Subscriber,1962.0,Male,2016,01
2,202,2016-01-01 00:18:25,2016-01-01 00:21:47,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24689,Subscriber,1962.0,Female,2016,01
3,248,2016-01-01 00:23:13,2016-01-01 00:27:21,3209,Brunswick St,40.724176,-74.050656,3203,Hamilton Park,40.727596,-74.044247,24693,Subscriber,1984.0,Male,2016,01
4,903,2016-01-01 01:03:20,2016-01-01 01:18:24,3195,Sip Ave,40.730743,-74.063784,3210,Pershing Field,40.742677,-74.051789,24573,Customer,NaN,Unknown,2016,01

In [21]:
df['Gender'] =df['Gender'].astype(str)

In [22]:
df.dtypes

Trip Duration                       int64
Start Time                 datetime64[ns]
Stop Time                  datetime64[ns]
Start Station ID                    int64
Start Station Name                 object
Start Station Latitude            float64
Start Station Longitude           float64
End Station ID                      int64
End Station Name                   object
End Station Latitude              float64
End Station Longitude             float64
Bike ID                             int64
User Type                          object
Birth Year                        float64
Gender                             object
year_of_ride                        int64
Month                              object
dtype: object

In [23]:
weather_data = pd.read_csv('newark_airport_2016.csv')

In [24]:
weather_data.head()

,STATION,NAME,DATE,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TSUN,WDF2,WDF5,WSF2,WSF5
0,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-01,12.75,NaN,0.0,0.0,0.0,41,43,34,NaN,270,280.0,25.9,35.1
1,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-02,9.40,NaN,0.0,0.0,0.0,36,42,30,NaN,260,260.0,21.0,25.1
2,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-03,10.29,NaN,0.0,0.0,0.0,37,47,28,NaN,270,250.0,23.9,30.0
3,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-04,17.22,NaN,0.0,0.0,0.0,32,35,14,NaN,330,330.0,25.9,33.1
4,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-05,9.84,NaN,0.0,0.0,0.0,19,31,10,NaN,360,350.0,25.1,31.1

In [25]:
weather_data.isnull().sum()

STATION      0
NAME         0
DATE         0
AWND         0
PGTM       366
PRCP         0
SNOW         0
SNWD         0
TAVG         0
TMAX         0
TMIN         0
TSUN       366
WDF2         0
WDF5         2
WSF2         0
WSF5         2
dtype: int64

In [26]:
weather_data.count()

STATION    366
NAME       366
DATE       366
AWND       366
PGTM         0
PRCP       366
SNOW       366
SNWD       366
TAVG       366
TMAX       366
TMIN       366
TSUN         0
WDF2       366
WDF5       364
WSF2       366
WSF5       364
dtype: int64

In [27]:
weather_data=weather_data.drop(columns = ['PGTM' , 'TSUN'] )

In [28]:
weather_data.isnull().sum()

STATION    0
NAME       0
DATE       0
AWND       0
PRCP       0
SNOW       0
SNWD       0
TAVG       0
TMAX       0
TMIN       0
WDF2       0
WDF5       2
WSF2       0
WSF5       2
dtype: int64

In [29]:
weather_data.dtypes

STATION     object
NAME        object
DATE        object
AWND       float64
PRCP       float64
SNOW       float64
SNWD       float64
TAVG         int64
TMAX         int64
TMIN         int64
WDF2         int64
WDF5       float64
WSF2       float64
WSF5       float64
dtype: object

In [30]:
df.count()

Trip Duration              247584
Start Time                 247584
Stop Time                  247584
Start Station ID           247584
Start Station Name         247584
Start Station Latitude     247584
Start Station Longitude    247584
End Station ID             247584
End Station Name           247584
End Station Latitude       247584
End Station Longitude      247584
Bike ID                    247584
User Type                  247204
Birth Year                 228585
Gender                     247584
year_of_ride               247584
Month                      247584
dtype: int64

In [31]:
df.isnull().sum()

Trip Duration                  0
Start Time                     0
Stop Time                      0
Start Station ID               0
Start Station Name             0
Start Station Latitude         0
Start Station Longitude        0
End Station ID                 0
End Station Name               0
End Station Latitude           0
End Station Longitude          0
Bike ID                        0
User Type                    380
Birth Year                 18999
Gender                         0
year_of_ride                   0
Month                          0
dtype: int64

In [32]:
df.head()

,Trip Duration,Start Time,Stop Time,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID,User Type,Birth Year,Gender,year_of_ride,Month
0,362,2016-01-01 00:02:52,2016-01-01 00:08:54,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,24647,Subscriber,1964.0,Female,2016,01
1,200,2016-01-01 00:18:22,2016-01-01 00:21:42,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24605,Subscriber,1962.0,Male,2016,01
2,202,2016-01-01 00:18:25,2016-01-01 00:21:47,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24689,Subscriber,1962.0,Female,2016,01
3,248,2016-01-01 00:23:13,2016-01-01 00:27:21,3209,Brunswick St,40.724176,-74.050656,3203,Hamilton Park,40.727596,-74.044247,24693,Subscriber,1984.0,Male,2016,01
4,903,2016-01-01 01:03:20,2016-01-01 01:18:24,3195,Sip Ave,40.730743,-74.063784,3210,Pershing Field,40.742677,-74.051789,24573,Customer,NaN,Unknown,2016,01

In [33]:
df['Bike ID'].nunique()

566

In [34]:
weather_data.head()

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,WDF2,WDF5,WSF2,WSF5
0,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-01,12.75,0.0,0.0,0.0,41,43,34,270,280.0,25.9,35.1
1,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-02,9.40,0.0,0.0,0.0,36,42,30,260,260.0,21.0,25.1
2,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-03,10.29,0.0,0.0,0.0,37,47,28,270,250.0,23.9,30.0
3,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-04,17.22,0.0,0.0,0.0,32,35,14,330,330.0,25.9,33.1
4,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-05,9.84,0.0,0.0,0.0,19,31,10,360,350.0,25.1,31.1

In [35]:
df.columns

Index(['Trip Duration', 'Start Time', 'Stop Time', 'Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID', 'User Type',
       'Birth Year', 'Gender', 'year_of_ride', 'Month'],
      dtype='object')

In [36]:
station_columns = ['Start Station ID',
       'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude', 'Bike ID']
Station_info = df[station_columns].copy()

In [37]:
Station_info.head()

,Start Station ID,Start Station Name,Start Station Latitude,Start Station Longitude,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID
0,3186,Grove St PATH,40.719586,-74.043117,3209,Brunswick St,40.724176,-74.050656,24647
1,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24605
2,3186,Grove St PATH,40.719586,-74.043117,3213,Van Vorst Park,40.718489,-74.047727,24689
3,3209,Brunswick St,40.724176,-74.050656,3203,Hamilton Park,40.727596,-74.044247,24693
4,3195,Sip Ave,40.730743,-74.063784,3210,Pershing Field,40.742677,-74.051789,24573

In [38]:
Trip_columns = ['Bike ID', 'Trip Duration', 'Start Time', 'Stop Time' ,'Month']
Trip_info = df [Trip_columns].copy()

In [39]:
Trip_info.head()

   Bike ID  Trip Duration          Start Time           Stop Time Month
0    24647            362 2016-01-01 00:02:52 2016-01-01 00:08:54    01
1    24605            200 2016-01-01 00:18:22 2016-01-01 00:21:42    01
2    24689            202 2016-01-01 00:18:25 2016-01-01 00:21:47    01
3    24693            248 2016-01-01 00:23:13 2016-01-01 00:27:21    01
4    24573            903 2016-01-01 01:03:20 2016-01-01 01:18:24    01

In [40]:
User_columns = ['Bike ID', 'User Type',
       'Birth Year', 'Gender']
User_info =df[User_columns].copy()

In [41]:
User_info.head()

   Bike ID   User Type  Birth Year   Gender
0    24647  Subscriber      1964.0   Female
1    24605  Subscriber      1962.0     Male
2    24689  Subscriber      1962.0   Female
3    24693  Subscriber      1984.0     Male
4    24573    Customer         NaN  Unknown

In [42]:
Station_info.duplicated().value_counts()

True     124018
False    123566
Name: count, dtype: int64

In [43]:
Station_info.drop_duplicates(subset = ['Start Station ID'], inplace =True )

In [44]:
col_to_drop =[ 'End Station ID', 'End Station Name',
       'End Station Latitude', 'End Station Longitude']
  
Start_station_info = Station_info.drop(columns =col_to_drop)

In [45]:
End_col_to_drop = ['Start Station ID','Start Station Name', 'Start Station Latitude','Start Station Longitude']
End_Station_info=Station_info.drop(columns =End_col_to_drop)

In [46]:
End_Station_info.head()

,End Station ID,End Station Name,End Station Latitude,End Station Longitude,Bike ID
0,3209,Brunswick St,40.724176,-74.050656,24647
3,3203,Hamilton Park,40.727596,-74.044247,24693
4,3210,Pershing Field,40.742677,-74.051789,24573
7,3203,Hamilton Park,40.727596,-74.044247,24625
8,3214,Essex Light Rail,40.712774,-74.036486,24429

In [47]:
End_Station_info.drop_duplicates(subset = ['End Station ID'], inplace =True)

In [48]:
Start_station_info.columns

Index(['Start Station ID', 'Start Station Name', 'Start Station Latitude',
       'Start Station Longitude', 'Bike ID'],
      dtype='object')

In [49]:
Start_station_info.dtypes

Start Station ID             int64
Start Station Name          object
Start Station Latitude     float64
Start Station Longitude    float64
Bike ID                      int64
dtype: object

In [50]:
Start_station_info.duplicated().value_counts()

False    51
Name: count, dtype: int64

In [51]:
from sqlalchemy import create_engine

# Format: postgresql://username:password@host:port/database
engine = create_engine('postgresql://postgres:postgres@localhost:5432/CitiBike_Data')

# Insert data into the existing 'trips' table
Start_station_info.to_sql('Start_Station_Information', con=engine, if_exists='append', index=False)

IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "Start+Station_Information_pkey"
DETAIL:  Key ("Start Station ID")=(3186) already exists.

[SQL: INSERT INTO "Start_Station_Information" ("Start Station ID", "Start Station Name", "Start Station Latitude", "Start Station Longitude", "Bike ID") VALUES (%(Start_Station_ID__0)s, %(Start_Station_Name__0)s, %(Start_Station_Latitude__0)s, %(Start_Stat ... 6790 characters truncated ... tation_Name__50)s, %(Start_Station_Latitude__50)s, %(Start_Station_Longitude__50)s, %(Bike_ID__50)s)]
[parameters: {'Start_Station_ID__0': 3186, 'Start_Station_Longitude__0': -74.04311746358871, 'Bike_ID__0': 24647, 'Start_Station_Latitude__0': 40.71958611647166, 'Start_Station_Name__0': 'Grove St PATH', 'Start_Station_ID__1': 3209, 'Start_Station_Longitude__1': -74.0506564, 'Bike_ID__1': 24693, 'Start_Station_Latitude__1': 40.7241765, 'Start_Station_Name__1': 'Brunswick St', 'Start_Station_ID__2': 3195, 'Start_Station_Longitude__2': -74.06378388404846, 'Bike_ID__2': 24573, 'Start_Station_Latitude__2': 40.73074262530658, 'Start_Station_Name__2': 'Sip Ave', 'Start_Station_ID__3': 3211, 'Start_Station_Longitude__3': -74.046304543, 'Bike_ID__3': 24625, 'Start_Station_Latitude__3': 40.72152515, 'Start_Station_Name__3': 'Newark Ave', 'Start_Station_ID__4': 3187, 'Start_Station_Longitude__4': -74.03805095, 'Bike_ID__4': 24429, 'Start_Station_Latitude__4': 40.7211236, 'Start_Station_Name__4': 'Warren St', 'Start_Station_ID__5': 3183, 'Start_Station_Longitude__5': -74.0334588, 'Bike_ID__5': 24377, 'Start_Station_Latitude__5': 40.7162469, 'Start_Station_Name__5': 'Exchange Place', 'Start_Station_ID__6': 3213, 'Start_Station_Longitude__6': -74.047726625, 'Bike_ID__6': 24605, 'Start_Station_Latitude__6': 40.71848892, 'Start_Station_Name__6': 'Van Vorst Park', 'Start_Station_ID__7': 3193, 'Start_Station_Longitude__7': -74.07840594649315, 'Bike_ID__7': 24606, 'Start_Station_Latitude__7': 40.7246050998869, 'Start_Station_Name__7': 'Lincoln Park', 'Start_Station_ID__8': 3194, 'Start_Station_Longitude__8': -74.06762212514877, 'Bike_ID__8': 24675, 'Start_Station_Latitude__8': 40.7253399253558, 'Start_Station_Name__8': 'McGinley Square', 'Start_Station_ID__9': 3202, 'Start_Station_Longitude__9': -74.0337589, 'Bike_ID__9': 24687, 'Start_Station_Latitude__9': 40.7272235, 'Start_Station_Name__9': 'Newport PATH' ... 155 parameters truncated ... 'Start_Station_ID__41': 3276, 'Start_Station_Longitude__41': -74.04281705617905, 'Bike_ID__41': 24686, 'Start_Station_Latitude__41': 40.71458403535893, 'Start_Station_Name__41': 'Marin Light Rail', 'Start_Station_ID__42': 3273, 'Start_Station_Longitude__42': -74.04288411140442, 'Bike_ID__42': 24525, 'Start_Station_Latitude__42': 40.72165072487999, 'Start_Station_Name__42': 'Manila & 1st', 'Start_Station_ID__43': 3275, 'Start_Station_Longitude__43': -74.03891444206238, 'Bike_ID__43': 24703, 'Start_Station_Latitude__43': 40.71835519823214, 'Start_Station_Name__43': 'Columbus Drive', 'Start_Station_ID__44': 3274, 'Start_Station_Longitude__44': -74.08593088388443, 'Bike_ID__44': 24480, 'Start_Station_Latitude__44': 40.704957516728605, 'Start_Station_Name__44': 'Bethune Center', 'Start_Station_ID__45': 3281, 'Start_Station_Longitude__45': -74.0572714805603, 'Bike_ID__45': 24603, 'Start_Station_Latitude__45': 40.74590996631558, 'Start_Station_Name__45': 'Leonard Gordon Park', 'Start_Station_ID__46': 3271, 'Start_Station_Longitude__46': -74.08801227807997, 'Bike_ID__46': 24417, 'Start_Station_Latitude__46': 40.69263996618329, 'Start_Station_Name__46': 'Danforth Light Rail', 'Start_Station_ID__47': 3269, 'Start_Station_Longitude__47': -74.05038893222809, 'Bike_ID__47': 26254, 'Start_Station_Latitude__47': 40.72601172964625, 'Start_Station_Name__47': 'Brunswick & 6th', 'Start_Station_ID__48': 3280, 'Start_Station_Longitude__48': -74.07126188278198, 'Bike_ID__48': 26267, 'Start_Station_Latitude__48': 40.71928220070702, 'Start_Station_Name__48': 'Astor Place', 'Start_Station_ID__49': 3426, 'Start_Station_Longitude__49': -74.06860113143921, 'Bike_ID__49': 26294, 'Start_Station_Latitude__49': 40.70965083364061, 'Start_Station_Name__49': 'JCBS Depot', 'Start_Station_ID__50': 3277, 'Start_Station_Longitude__50': -74.06661093235016, 'Bike_ID__50': 26266, 'Start_Station_Latitude__50': 40.71435836870427, 'Start_Station_Name__50': 'Communipaw & Berry Lane'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [ ]:
End_Station_info.columns

In [ ]:
End_Station_info.dtypes

In [ ]:
from sqlalchemy import create_engine

# Format: postgresql://username:password@host:port/database
engine = create_engine('postgresql://postgres:postgres@localhost:5432/CitiBike_Data')

# Insert data into the existing 'trips' table
End_Station_info.to_sql('End_Station_information', con=engine, if_exists='append', index=False)

In [ ]:
End_Station_info.head()

In [ ]:
Trip_info.head()

In [ ]:
Trip_info.columns

In [ ]:
Trip_info['Bike ID'].duplicated().value_counts()

In [ ]:
Trip_info.dtypes

In [ ]:
# Format: postgresql://username:password@host:port/database
engine = create_engine('postgresql://postgres:postgres@localhost:5432/CitiBike_Data')

# Insert data into the existing 'trips' table
Trip_info.to_sql('Trip_information', con=engine, if_exists='append', index=False)

In [ ]:
User_info.head()

In [ ]:
User_info = User_info.dropna()

In [ ]:
User_info.isnull().sum()

In [ ]:
User_info.columns

In [ ]:
User_info.dtypes

In [ ]:
# Format: postgresql://username:password@host:port/database
engine = create_engine('postgresql://postgres:postgres@localhost:5432/CitiBike_Data')

# Insert data into the existing 'trips' table
User_info.to_sql('User_information', con=engine, if_exists='append', index=False)

In [52]:
weather_data.head()

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,WDF2,WDF5,WSF2,WSF5
0,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-01,12.75,0.0,0.0,0.0,41,43,34,270,280.0,25.9,35.1
1,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-02,9.40,0.0,0.0,0.0,36,42,30,260,260.0,21.0,25.1
2,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-03,10.29,0.0,0.0,0.0,37,47,28,270,250.0,23.9,30.0
3,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-04,17.22,0.0,0.0,0.0,32,35,14,330,330.0,25.9,33.1
4,USW00014734,"NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US",2016-01-05,9.84,0.0,0.0,0.0,19,31,10,360,350.0,25.1,31.1

In [54]:
weather_data.columns

Index(['STATION', 'NAME', 'DATE', 'AWND', 'PRCP', 'SNOW', 'SNWD', 'TAVG',
       'TMAX', 'TMIN', 'WDF2', 'WDF5', 'WSF2', 'WSF5'],
      dtype='object')

In [56]:
weather_data.dtypes

STATION     object
NAME        object
DATE        object
AWND       float64
PRCP       float64
SNOW       float64
SNWD       float64
TAVG         int64
TMAX         int64
TMIN         int64
WDF2         int64
WDF5       float64
WSF2       float64
WSF5       float64
dtype: object

In [58]:
weather_data['DATE'] =pd.to_datetime(weather_data['DATE'])

In [62]:
weather_data.dtypes

STATION            object
NAME               object
DATE       datetime64[ns]
AWND              float64
PRCP              float64
SNOW              float64
SNWD              float64
TAVG                int64
TMAX                int64
TMIN                int64
WDF2                int64
WDF5              float64
WSF2              float64
WSF5              float64
dtype: object

In [66]:
# Format: postgresql://username:password@host:port/database
engine4 = create_engine('postgresql://postgres:postgres@localhost:5432/CitiBike_Data')

# Insert data into the existing 'trips' table
weather_data.to_sql('WeatherData', con=engine4, if_exists='append', index=False)

366